# Change these first
owner: thewillwilson # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Main Site
    url: https://willwilson.uk
  - name: Home Assistant
    url: https://ha.willwilson.uk
  - name: RTR2-LON (1&1 VPS)
    url: rtr2-lon.n.willwilson.uk
    check: "tcp-ping"
    port: 8291

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.willwilson.uk
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Will Wilson Status
  introTitle: "Will Wilson (AS214818) Service Status"
  introMessage: Service status is updated approximately every 5-30 minutes. Charts are updated less frequently. Subscribe to updates by watching all repo activity on GitHub - https://github.com/thewillwilson/upptime
  theme: light
  navbar:
    - title: Email NOC
      href: mailto:noc@willwilson.uk
    - title: Email Abuse
      href: mailto:abuse@willwilson.uk
    - title: Email Peering
      href: mailto:peering@willwilson.uk

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
